baseURL = "http://example.org/"
languageCode = "en-us"
title = "Mike Charles"
theme = "hugo-theme-cleanwhite"

paginate = 5 #frontpage pagination
hasCJKLanguage = true
[outputs]
home = ["HTML", "RSS"]

[params]
  header_image = "images/edmonton.jpg"
  SEOTitle = "Mike Charles"
  description = "my desc"
  keyword = "list of key wrods"
  slogan = "Love code. Hate servers."

#  image_404 = "img/404-bg.jpg"
#  title_404 = "你来到了没有知识的荒原 :("
  # Sidebar settings
  sidebar_about_description = "Dad, techy, Arsenal fan"
  sidebar_avatar = "images/me.jpg"      # use absolute URL, seeing it's used in both `/` and `/about/`

  featured_tags = true
  featured_condition_size = 2

  [params.social]
  rss       = true
  email     = "email@mikecharl.es"
  facebook  = "https://www.facebook.com/M1keCharles"
  twitter   = "looknoservers"
  linkedin  = "https://www.linkedin.com/in/mikecharles/"
  github    = "https://github.com/RIMikeC"

  friends = true
  bookmarks = false
  about_me = true

  [[params.friend_link]]
  title = "Linda的博客"
  href =  "https://zhaozhihan.com"

  bookmarks = true

