baseURL = "http://nomorewebservers.s3-website-eu-west-1.amazonaws.com"
languageCode = "en-us"
title = "Mike Charles"
theme = "hugo-theme-cleanwhite"

paginate = 5 #frontpage pagination
hasCJKLanguage = true
[outputs]
home = ["HTML", "RSS"]

[params]
  header_image = "images/edmonton.jpg"
  SEOTitle = "Mike Charles"
  description = "my desc"
  keyword = "list of key wrods"
  slogan = "Love code. Hate servers."

#  image_404 = "img/404-bg.jpg"
#  title_404 = "你来到了没有知识的荒原 :("
  # Sidebar settings
  sidebar_about_description = "Dad, techy, Arsenal fan"
  sidebar_avatar = "images/me.jpg"      # use absolute URL, seeing it's used in both `/` and `/about/`

  featured_tags = true
  featured_condition_size = 2

  [params.social]
  rss       = true
  email     = "email@mikecharl.es"
  facebook  = "https://www.facebook.com/M1keCharles"
  twitter   = "looknoservers"
  linkedin  = "https://www.linkedin.com/in/mikecharles/"
  github    = "https://github.com/RIMikeC"

  friends = true
  bookmarks = true
  about_me = true

  [[params.bookmark_link]]
  title =  "Martin Fowler"
  href =  "https://martinfowler.com"
  [[params.bookmark_link]]
  title = "RITech"
  href =  "https://www.ritechstyle.com/"
  [[params.bookmark_link]]
  title = "AWS"
  href = "https://www.amazon.com/ap/signin"
  [[params.bookmark_link]]
  title =  "hugo"
  href = "https://gohugo.io/"
  [[params.bookmark_link]]
  title = "The Agile Manifesto"
  href = "http://agilemanifesto.org/"


  [[params.friend_link]]
  title = "Jeff"
  href =  "https://aws.amazon.com/blogs/aws/author/jbarr/"


