baseURL = "http://mikecharl.es"
languageCode = "en-us"
title = "Mike Charles"
theme = "hugo-theme-cleanwhite"
googleAnalytics="UA-136875413-1"
showtoc = false

paginate = 5 #frontpage pagination
hasCJKLanguage = true
[outputs]
home = ["HTML", "RSS"]

[params]
  header_image = "images/edmonton.jpg"
  SEOTitle = "Mike Charles"
  description = "serverless life"
  keyword = "list of key words"
  slogan = "Love code. Hate servers."

  image_404 = "images/404-bg.jpg"
  title_404 = "how did you get here?"

  # Sidebar settings
  sidebar_about_description = "Dad, techy, Arsenal fan"
  sidebar_avatar = "images/me.jpg"      # use absolute URL, seeing it's used in both `/` and `/about/`

  featured_tags = true
  featured_condition_size = 1

  [params.social]
  rss       = true
  email     = "mailto:mcriverisland@gmail.com"
  facebook  = "https://www.facebook.com/M1keCharles"
  twitter   = "https://twitter.com/looknoservers"
  linkedin  = "https://www.linkedin.com/in/mikecharles/"
  github    = "https://github.com/RIMikeC"

  friends = true
  bookmarks = true
  about_me = true

  [[params.friend_link]]
  title = "Jeff"
  href =  "https://aws.amazon.com/blogs/aws/author/jbarr/"

  [[params.bookmark_link]]
  title =  "Martin Fowler"
  href =  "https://martinfowler.com"
  [[params.bookmark_link]]
  title = "RITech"
  href =  "https://www.ritechstyle.com/"
  [[params.bookmark_link]]
  title = "AWS"
  href = "https://www.amazon.com/ap/signin"
  [[params.bookmark_link]]
  title =  "hugo"
  href = "https://gohugo.io/"
  [[params.bookmark_link]]
  title = "The Agile Manifesto"
  href = "http://agilemanifesto.org/"

  [[params.addtional_menus]]
  title =  "BOOKS"
  href =  "/top/books/"
  [[params.addtional_menus]]
  title =  "ABOUT"
  href =  "/top/about/"

